apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2021-08-13T18:49:07Z"
  generation: 1
  labels:
    app: legacy-weather-web
  name: legacy-weather-web
  namespace: default
  resourceVersion: "32306"
  selfLink: /apis/apps/v1/namespaces/default/deployments/legacy-weather-web
  uid: d2791aff-6991-4674-a11f-d9fac5d7717d
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: legacy-weather-web
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: legacy-weather-web
    spec:
      containers:
      - image: caprilespe/legacy-weather-web:v1
        imagePullPolicy: IfNotPresent
        name: legacy-weather-web
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2021-08-13T18:49:21Z"
    lastUpdateTime: "2021-08-13T18:49:21Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2021-08-13T18:49:08Z"
    lastUpdateTime: "2021-08-13T18:49:21Z"
    message: ReplicaSet "legacy-weather-web-9f4754f55" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
